### ISSUE TITLE
implement batch-update

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-update-fs-rdb#12]
@DANS-KNAW/easy 
EASY-921

Implement update of multiple datasets (possibly all). Try to make it efficient by doing the updates in transactions that insert/update multiple records at once.

**Comment by PaulBoon** [comment]
The 'update' now can handle multiple datasets by the dataset id's specified as arguments on the command line or in a text file. 
The database records for a dataset are updated/inserted in a transaction that can be rolled back, thus making sure the database keeps consistent in case of an error.

**Comment by PaulBoon** [comment]
Updating a 1000 items (files and folders) takes about 15 seconds, regardless how they are organised.
